apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: team2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
      - name: harbor-secret
      containers:
      - name: api
        image: 10.2.2.40:5000/library/kma-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000

