apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-web
  template:
    metadata:
      labels:
        app: my-web
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-workernode4
      containers:
        - name: my-web
          image: my-web:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

