apiVersion: v1
kind: Secret
metadata:
  name: kma-api-env
  namespace: team2
type: Opaque
stringData:
  KMA_AUTHKEY: "MmNnsQppQqGjZ7EKaaKhgQ"
---
apiVersion: v1
kind: Secret
metadata:
  name: energy-api-env
  namespace: team2
type: Opaque
stringData:
  EMP_API_KEY: "8D4GI7rDQnO4ukBpn4QTbSeT5H9a8eahji7E2td5"
  DATA_GO_KR_SERVICE_KEY: "93f2e3191276074224c438872e7cc3a95b6bcff3adbf538ceb8dba2938a233d5"
  KPX_ODCLOUD_DATASET_URL: "https://api.odcloud.kr/api/15040818/v1/uddi:0873d163-4ed7-49f9-bf95-8eb5c7e35fad"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: map-web-config
  namespace: team2
data:
  NAVER_MAP_CLIENT_ID: "zoqel2ur4g"

